### ISSUE TITLE
Not existent dependency

### ISSUE THREAD

**Issue by anivle** [jaz303/git-clone#10]
On `npm-install` fails with following error:

npm ERR! prepareGitDep npm ERR! code E404
npm ERR! prepareGitDep npm ERR! 404 Not Found - GET https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.7.2.tgz
npm ERR! prepareGitDep npm ERR! 404 
npm ERR! prepareGitDep npm ERR! 404  'websocket-driver@0.7.2' is not in the npm registry.
npm ERR! prepareGitDep npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! prepareGitDep npm ERR! 404 It was specified as a dependency of 'git-clone-1e7560c9'
npm ERR! prepareGitDep npm ERR! 404 
npm ERR! prepareGitDep npm ERR! 404 Note that you can also install from a
npm ERR! prepareGitDep npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! prepareGitDep 

Mentioned link returns 404, but the same for 0.7.3 is ok

 npm --version
6.11.3
node --version
v10.17.0

**Comment by jaz303** [comment]
You must be using an unofficial fork; `websocket-driver` is not, and has never been, a dependency of `git-clone`.
