### ISSUE TITLE
Webpack error 'child_process' module not found.

### ISSUE THREAD

**Issue by browerjosiahdev** [jaz303/git-clone#2]
Webpack doesn't seem to like the 'child_process' native module, because it try's to include it but can't find it. I was able to work around this issue doing:

```
var spawn;
try {
  spawn = window['require']('child_process').spawn;
} catch (err) {
  spawn = {};
}
```

There may be a better way to do this, and it seems like more of an issue with Webpack (I will post an issue there as well), I just figured I would make you aware.

**Comment by jaz303** [comment]
Thanks for the heads up... I think this is something that should be solved by Webpack.
