### ISSUE TITLE
windows download mygitlab RequestError: unable to verify the first certificate #32

### ISSUE THREAD

**Issue by skyweaver213** [jaz303/git-clone#5]
Hello, I use the download-git-repo to download, if the address is mygitlab.com, it will be failed when running on the windows os. I seek help for  the owner  of download-git-repo.He said it dependence on git-clone. so I hope to get your help, thank you very much!

![0180306144337](https://user-images.githubusercontent.com/5363176/37017957-80951626-214d-11e8-8df1-3b1f4d5e6a69.png)

![20180306144438](https://user-images.githubusercontent.com/5363176/37017799-eaff08a6-214c-11e8-8415-62d77b17bb17.png)

**Comment by jaz303** [comment]
Closing this because it's been three years so not sure if you're still experiencing this problem (sorry that's on me). Feel free to re-open if this is still causing you trouble.
